General:
  ServiceXBackendName: uproot
  OutputDirectory: ServiceXData_uproot
  OutputFormat: parquet
  WriteOutputDict: out_uproot
  
Sample:
  - Name: ttH
    RucioDID: user.kchoi:user.kchoi.example.ttH
    Tree: nominal
    FuncADL: "Select(lambda event: {'jet_e': event.jet_e, 'jet_pt': event.jet_pt, 'met_met': event.met_met})"
  - Name: ttW
    RucioDID: user.kchoi:user.kchoi.example.ttW
    Tree: nominal
    FuncADL: "Select(lambda event: {'jet_e': event.jet_e, 'jet_pt': event.jet_pt, 'met_met': event.met_met})"
  - Name: ttZ
    RucioDID: user.kchoi:user.kchoi.example.ttZ
    Tree: nominal
    Filter: ""
    Columns: jet_e, jet_pt