General:
  ServiceXBackendName: uproot_river
  OutputDirectory: ServiceXData_uproot
  OutputFormat: root
  ZipROOTColumns: True
  WriteOutputDict: out_uproot
  IgnoreServiceXCache: False
  
Sample:
  - Name: ttH
    RucioDID: user.mgeyik:user.mgeyik.mc16_13TeV.346344.PhPy8EG_ttH125_1l.SGTOP1.e7148_a875_r9364_p4346.ll.b_out.root, 
             user.mgeyik:user.mgeyik.mc16_13TeV.346344.PhPy8EG_ttH125_1l.SGTOP1.e7148_a875_r10201_p4346.ll.d_out.root
    Tree: nominal
    FuncADL: "Select(lambda event: {'jet_e': event.jet_e, 'jet_pt': event.jet_pt, 'met_met': event.met_met})"
  - Name: ttH
    RucioDID: user.mgeyik:user.mgeyik.mc16_13TeV.346344.PhPy8EG_ttH125_1l.SGTOP1.e7148_a875_r9364_p4346.ll.b_out.root, 
             user.mgeyik:user.mgeyik.mc16_13TeV.346344.PhPy8EG_ttH125_1l.SGTOP1.e7148_a875_r10201_p4346.ll.d_out.root
    Tree: sumWeights
    FuncADL: "Select(lambda event: {'dsid': event.dsid, 'totalEventsWeighted': event.totalEventsWeighted})"
  - Name: ttW
    RucioDID: user.mgeyik:user.mgeyik.mc16_13TeV.410155.aMCPy8EG_ttW.SGTOP1.e5070_s3126_r10724_p4346.ll.b_out.root
    Tree: nominal
    Filter: ""
    Columns: jet_e, jet_pt
